<a href="https://colab.research.google.com/github/Victonier/CS523/blob/main/Pytorch_Tutorial_Part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from __future__ import print_function
import torch
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed



Section 1: Tensors
================
Please refer: https://pytorch.org/docs/stable/tensors.html

A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

<b>Task 1: Constructing Tensors</b>

a) Construct a 5x3 matrix, uninitialized:



In [ ]:
# The shape of the tensor is defined by the variable argument size
# Tensor is initialized with garbage values
x = torch.empty(5, 3)
print(x)

tensor([[ 1.6399e-34,  0.0000e+00,  1.9021e-35],
        [ 0.0000e+00, -1.3565e+11,  4.5820e-41],
        [ 1.4013e-45,  0.0000e+00,  2.1019e-44],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


b) Construct a randomly initialized matrix:



In [ ]:
x = torch.rand(5, 3)
print(x)
print(x.size())
x.shape

tensor([[0.5912, 0.2074, 0.3439],
        [0.2879, 0.1988, 0.4856],
        [0.7823, 0.7591, 0.6336],
        [0.8972, 0.7790, 0.0655],
        [0.9163, 0.4170, 0.0775]])
torch.Size([5, 3])


torch.Size([5, 3])

c) Construct a matrix filled zeros and of dtype long:



In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


d) Construct a tensor directly from data:



In [ ]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


e) Create a tensor based on an existing tensor. 

Note: These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user



In [ ]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

# Generates random values from Normal distribution
# Uses the shape of the given tensor
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1034, -0.6877,  0.2843],
        [-0.3262,  1.0645,  0.7493],
        [ 0.6175,  0.1917, -0.4022],
        [-1.8715,  1.4590,  1.8939],
        [-0.8562, -0.1459, -0.9315]])


<b>Task 2: Get the size of the tensor </b>

Note: torch.Size is in fact a tuple, so it supports all tuple operations.



In [ ]:
print(x.size())
# print(x.size())
x.shape

torch.Size([5, 3])


torch.Size([5, 3])

<b>Task 3: Operations</b>

a) Addition: syntax 1



In [ ]:
p = torch.rand(5, 3)
q = torch.rand(5, 3)
print(p + q)

tensor([[0.9180, 0.9165, 0.8618],
        [0.8242, 0.1714, 1.0875],
        [1.1863, 1.0715, 0.6796],
        [1.0337, 1.1458, 1.6569],
        [0.3050, 0.7076, 1.4855]])


b) Addition: syntax 2



In [ ]:
print(torch.add(p, q))

tensor([[0.9180, 0.9165, 0.8618],
        [0.8242, 0.1714, 1.0875],
        [1.1863, 1.0715, 0.6796],
        [1.0337, 1.1458, 1.6569],
        [0.3050, 0.7076, 1.4855]])


c) Addition: providing an output tensor as argument



In [ ]:
result = torch.empty(5, 3)
torch.add(p, q, out=result)
print(result)

tensor([[0.9180, 0.9165, 0.8618],
        [0.8242, 0.1714, 1.0875],
        [1.1863, 1.0715, 0.6796],
        [1.0337, 1.1458, 1.6569],
        [0.3050, 0.7076, 1.4855]])


d) Addition: in-place



In [ ]:
# adds x to y
q.add_(p)
print(q)

tensor([[0.9180, 0.9165, 0.8618],
        [0.8242, 0.1714, 1.0875],
        [1.1863, 1.0715, 0.6796],
        [1.0337, 1.1458, 1.6569],
        [0.3050, 0.7076, 1.4855]])


Note: Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

<b>Task 4: Misc Operations </b>

a) Indexing



In [ ]:
print(result)
print(result[:, 1])

tensor([[0.9180, 0.9165, 0.8618],
        [0.8242, 0.1714, 1.0875],
        [1.1863, 1.0715, 0.6796],
        [1.0337, 1.1458, 1.6569],
        [0.3050, 0.7076, 1.4855]])
tensor([0.9165, 0.1714, 1.0715, 1.1458, 0.7076])


b) Resizing



In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


c) Permute

Used for image data where order of data is important

In [ ]:
x = torch.randn(3,224,224)
y = x.permute(1,2,0)
print(x.size(), y.size())

torch.Size([3, 224, 224]) torch.Size([224, 224, 3])


d) Accessing 



In [ ]:
x = torch.randn(1) # std norm dist vs rand: uniform [0,1)
print(x)
print(x.item()) # works for tensors with single value

x = torch.randn(2, 2)
print(x)
print(x.tolist()) # works for tensors with multiple values

tensor([-0.2117])
-0.21173211932182312
tensor([[ 1.1036,  0.0842],
        [-1.6334,  0.7951]])
[[1.1036202907562256, 0.08422975987195969], [-1.6334466934204102, 0.7951104640960693]]


Section 2: NumPy 
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

a) Converting a Torch Tensor to a NumPy Array




In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

Note: See how the numpy array changed in value.



In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


b) Converting NumPy Array to Torch Tensor

Note: see how changing the np array changed the Torch Tensor automatically



In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

Section 3: CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
# Devices available are 'cuda' and 'cpu'

x = torch.rand(5,3)
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[1.7038, 1.5289, 1.1912],
        [1.9412, 1.0138, 1.8623],
        [1.9674, 1.4602, 1.4017],
        [1.2006, 1.5367, 1.5383],
        [1.9503, 1.4044, 1.2570]], device='cuda:0')
tensor([[1.7038, 1.5289, 1.1912],
        [1.9412, 1.0138, 1.8623],
        [1.9674, 1.4602, 1.4017],
        [1.2006, 1.5367, 1.5383],
        [1.9503, 1.4044, 1.2570]], dtype=torch.float64)
